cmake_minimum_required(VERSION 3.8)
project(arm_cell_bringup)
find_package(ament_cmake REQUIRED)
install(DIRECTORY config launch DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(test_planning_launch tests/test_planning_launch.py)
  ament_add_pytest_test(test_camera_launch tests/test_camera_launch.py)
endif()
ament_package()
